customhost = "database-1.cyy7fpkhz3pq.us-east-1.rds.amazonaws.com"
customuser = "project"
custompass = "driveready"
customdb = "student"
custombucket = "project-driveready"
customregion = "us-east-1"
